name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Render
      run: |
        samples=64
        bounces=7
        ${{github.workspace}}/build/pt assets/cornell_box/cornell_box.json "github_${samples}_${bounces}.png" $samples $bounces 0
        echo "$(date)"                       >> metadata.txt
        echo "$(git rev-parse --short HEAD)" >> metadata.txt
        zip artefact.$(date +%s).zip ./*.png ./metadata.txt

    - name: Copy render artefact to file server
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "*.zip"
        target: "/var/www/files/render-artefacts"
